# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6902b2315c323b5ff53070c1ea093aca"
application_url = "https://hear-poultry-semester-neighbors.trycloudflare.com"
embedded = true
name = "student"
handle = "student-2"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hear-poultry-semester-neighbors.trycloudflare.com/auth/callback",
  "https://hear-poultry-semester-neighbors.trycloudflare.com/auth/shopify/callback",
  "https://hear-poultry-semester-neighbors.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "testwac.myshopify.com"
automatically_update_urls_on_dev = true
